
name: FastAPI CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: fastapi-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black isort codecov
      - name: Lint code
        run: |
          flake8 .
          black --check .
          isort --check-only .
      - name: Run tests
        run: pytest tests/ --cov=app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

  build-static:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      - name: Generate static Swagger UI
        run: |
          mkdir -p dist
          echo "<!DOCTYPE html><html><body><redoc spec-url='/openapi.json'></redoc><script src='https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js'></script></body></html>" > dist/index.html
          cp -r app/static/* dist/ || true
          curl http://localhost:8000/openapi.json -o dist/openapi.json || true

  deploy:
    runs-on: ubuntu-latest
    needs: build-static
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
